services:
  mysql:
    image: mysql:8.0.1
    container_name: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: i20213tn102
      MYSQL_USER: ordinario
      MYSQL_PASSWORD: ordinario2024
      MYSQL_DATABASE: ordinario_db
    ports:
      - "9200:3306"

      //volume apuntando a ordinario_edit
  web-ordinario-edit:
    build:
      context: ./ordinario_edit
      dockerfile: Dockerfile
    container_name: Ordinario-Edit
    ports:
      - "9101:80"

      
  web-ordinario:
    build:
      context: ./ordinario
      dockerfile: Dockerfile
    container_name: Ordinario
    ports:
      - "9100:80"



